version: '{build}'

image: Visual Studio 2019

environment:
  matrix:
    - GENERATOR: "Visual Studio 16 2019"
      CONFIG: Debug
    - GENERATOR: "Visual Studio 16 2019"
      CONFIG: Release

build_script:
  - cmake "-G%GENERATOR%" -H. -B_builds -DBUILD_TESTS=ON
  - cmake --build _builds --config "%CONFIG%"

test_script:
  - ps: cd _builds
  - ctest -VV -C "%CONFIG%"