name: Create Release

on:
  workflow_run:
    workflows: ["CMake on multiple platforms"]
    types:
      - completed
    tags:
      - '*.*.*' # This will match tags like 1.0.2, 2.1.3, etc.
    branches:
      - main  # Adjust the branch as needed

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: ./artifacts

      - name: Set up Node.js (if you're using it for changelog generation)
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Updated Node.js version

      - name: Install dependencies
        run: npm install -g conventional-changelog-cli

      - name: Generate Changelog
        run: npx conventional-changelog -p angular -i CHANGELOG.md -s

      - name: Create GitHub release
        run: |
          # Extract the tag name from the Git ref
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          
          # Define the document path based on the tag name
          DOCUMENT_PATH="./artifacts/doc/latex/queue-${TAG_NAME}.pdf"
          
          # Check if the document file exists
          if [ ! -f "$DOCUMENT_PATH" ]; then
            echo "Document file $DOCUMENT_PATH does not exist. Exiting."
            exit 1
          fi

          # Create a release using the GitHub CLI with the tag name as the release name
          gh release create "$TAG_NAME" CHANGELOG.md "$DOCUMENT_PATH" --title "$TAG_NAME" --notes "Changelog for $TAG_NAME"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}